Based on
https://pablormier.github.io/2017/09/05/a-tutorial-on-differential-evolution-with-python/
___

In [ ]:
!pip install benchmark_functions

In [ ]:
# differential evolution global optimization for the ackley multimodal objective function
from scipy.optimize import differential_evolution
import numpy as np
from numpy.random import rand
from numpy import exp
from numpy import sqrt
from numpy import cos
from numpy import e
from numpy import pi
import benchmark_functions as bf


# objective function
def objective(v):
	x, y = v
	return -20.0 * exp(-0.2 * sqrt(0.5 * (x**2 + y**2))) - exp(0.5 * (cos(2 * pi * x) + cos(2 * pi * y))) + e + 20


# define range for input
r_min, r_max = -10.0, 10.0
# define the bounds on the search
bounds = [(r_min, r_max),(r_min, r_max)]
# perform the differential evolution search
result = differential_evolution(objective, bounds, strategy="best1bin")
# summarize the result
print('Status: %s' % result['message'])
print('Total Evaluations: %d' % result['nfev'])
# evaluate solution
solution = result['x']
evaluation = objective(solution)
print('Solution: f(%s) = %.5f' % (solution, evaluation))

Status: Optimization terminated successfully.
Total Evaluations: 3213
Solution: f([0. 0.]) = 0.00000


In [ ]:
import benchmark_functions as bf
import numpy as np

def objective(v):
  return np.float64(bf.Ackley(n_dimensions=2)(v))

print(type(objective((5,5))))


def objective2(v):
	x, y = v
	return -20.0 * exp(-0.2 * sqrt(0.5 * (x**2 + y**2))) - exp(0.5 * (cos(2 * pi * x) + cos(2 * pi * y))) + e + 20

print(type(objective2((5,5))))

<class 'numpy.float64'>
<class 'numpy.float64'>


In [ ]:
a = [(3,2)] * 3 + [(1,2)] * 2
print(a)
print(len(a))

[(3, 2), (3, 2), (3, 2), (1, 2), (1, 2)]
5


In [ ]:
import numpy as np

popSize = 10

bounds = [(-2,2)] * 3 + [(1,2)] * 2

dim = len(bounds)

pop = np.random.rand(popSize, dim)

bmin, bmax = np.asarray(bounds).T

print(bmin)

[-2 -2 -2  1  1]


In [ ]:
import numpy as np

popSize = 10

bounds = [(-10,10)] * 5
dim = len(bounds)

randArr = np.random.rand(popSize, dim)

bmin, bmax = np.asarray(bounds).T

diff = np.fabs(bmin - bmax)


pop = bmin + randArr*diff

print(randArr)

print("\n")

print(pop)




[[0.2842868  0.89510777 0.15222064 0.25634391 0.52489459]
 [0.48520195 0.13040764 0.81271624 0.04373183 0.33782125]
 [0.97090696 0.90224545 0.35070933 0.97836239 0.31811379]
 [0.28146234 0.13886999 0.66437145 0.69856    0.0078207 ]
 [0.54130595 0.48339228 0.47605251 0.89572186 0.70494916]
 [0.0227934  0.16474251 0.69176303 0.7034817  0.08574046]
 [0.89710677 0.30137235 0.07780126 0.42397054 0.58890449]
 [0.23293919 0.38574009 0.38188096 0.80351152 0.79332352]
 [0.0563241  0.28913351 0.23143424 0.14792536 0.35088593]
 [0.0088517  0.02429224 0.44464619 0.78048292 0.19692787]]


[[-4.31426402  7.90215533 -6.95558715 -4.87312175  0.49789187]
 [-0.29596095 -7.3918472   6.25432487 -9.1253634  -3.24357508]
 [ 9.41813913  8.04490896 -2.98581332  9.56724779 -3.63772414]
 [-4.37075312 -7.22260012  3.28742898  3.97120004 -9.84358591]
 [ 0.82611895 -0.33215435 -0.47894982  7.91443724  4.09898321]
 [-9.54413198 -6.70514971  3.83526056  4.06963398 -8.28519081]
 [ 7.94213535 -3.97255295 -8.44397477 -

In [ ]:
import numpy as np
from numpy.random import rand
from numpy import exp
from numpy import sqrt
from numpy import cos
from numpy import e
from numpy import pi


def de(costF, bounds, dim=False, mut=0.8, CR=0.7, popSize=20, gens=1):
  if not dim:
    dim = len(bounds)

  randArr = rand(popSize, dim)

  bmin, bmax = np.asarray(bounds).T

  diff = np.fabs(bmin - bmax)

  pop = bmin + randArr * diff

  costEval = np.asarray([costF(ind) for ind in pop])

  bestIndex = np.argmin(costEval)
  bestValue = costEval[bestIndex]
  best = pop[bestIndex]

  while gens:
    for i in range(popSize):
      currentIndividual = pop[i]
      indices = [index for index in range(popSize) if index != i]
      print(indices)

    gens -= 1

  return bestIndex, best, costEval, pop, bestValue


def costF(v):
  x, y = v
  return -20.0 * exp(-0.2 * sqrt(0.5 * (x**2 + y**2))) - exp(0.5 * (cos(2 * pi * x) + cos(2 * pi * y))) + e + 20

bounds = [(-5,5)] * 2

ind, best, costEval, pop, bestValue = de(costF, bounds)

print("Population:")
print(pop)
print("\n")
print("Cost Evaluations:")
print(costEval)
print("\n")
print("Best individual's index:", ind)
print("Best individual's value:", bestValue)
print("Best:", best)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
[0, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
[0, 1, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
[0, 1, 2, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
[0, 1, 2, 3, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
[0, 1, 2, 3, 4, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
[0, 1, 2, 3, 4, 5, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
[0, 1, 2, 3, 4, 5, 6, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
[0, 1, 2, 3, 4, 5, 6, 7, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 12, 13, 14, 15, 16, 17, 18, 19]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 13, 14, 15, 16, 17, 18, 19]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 13, 14, 15, 16, 17, 18, 19]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 14, 15, 16, 17, 18, 19]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 15, 1

In [2]:
import numpy as np

a = np.arange(10)
print(a)

clipped = np.clip(a,2,6)
print(clipped)

[0 1 2 3 4 5 6 7 8 9]
[2 2 2 3 4 5 6 6 6 6]


In [4]:
import numpy as np

CR = 0.8
dim = 2

cross_points = np.random.rand(dim) < CR

print(cross_points)

[ True  True]


In [28]:
import numpy as np

arr0 = np.random.rand(10)
arr = -2 + np.fabs(arr0*(-2-2))

print(arr[arr > 1],">1\n")
arr[arr > 1] = -2 + np.fabs(np.random.rand()*(-2-2))
print(arr[arr < -1],"<-1\n")
arr[arr < -1] = -2 + np.fabs(np.random.rand()*(-2-2))
print(arr)

[1.84500327 1.36386194 1.95152023 1.59353653] >1

[-1.17478002 -1.17478002 -1.17478002 -1.4221106  -1.17478002 -1.072168  ] <-1

[ 0.47629218 -1.98725173  0.21059732 -1.98725173 -1.98725173 -1.98725173
 -1.98725173  0.0360102  -0.61943559 -1.98725173]


In [91]:
# Crossing
import numpy as np

CR = 0.8
dim = 4
v = np.random.uniform(-2,2, size=dim)
ind = np.array((7,8,9,10))

trial = np.asarray([v[i] if np.random.rand()<CR else ind[i] for i in range(dim)])

print(v,"\n")
print(trial)

[ 1.07331893  0.77196028 -1.7171652  -0.65929528] 

[ 1.07331893  8.         -1.7171652  10.        ]


In [89]:
import numpy as np


def de(costF, bounds, dim=False, F=0.8, CR=0.8, popSize=False, gens=10):
  if not dim:
    dim = len(bounds)
  if not popSize:
    popSize = 10*dim

  # Population initialization

  #   - array of random numbers in range [0,1]
  pop = np.random.rand(popSize, dim)

  #   - converting bounds into array, T means transposed
  #   - it must be transposed so the boundaries are stored in bmin, bmax
  bmin, bmax = np.asarray(bounds).T

  #   - diff = search range of every parameter (array)
  #   - can't use bmax-bmin, it might result in 0
  diff = np.fabs(bmin - bmax)

  #   - get the population (pop) into boundaries (=ppl)
  #   - (can't do pop*bmax - it wouldn't cover numbers <0)
  ppl = bmin + pop * diff

  print(ppl[1])
  print(dim)

def costF(v):
	x, y = v
	return -20.0 * exp(-0.2 * sqrt(0.5 * (x**2 + y**2))) - exp(0.5 * (cos(2 * pi * x) + cos(2 * pi * y))) + e + 20


print(de(costF,[(-5,5)]*2))

[ 4.92039953 -1.71718569]
2
None


In [140]:
import numpy as np
from numpy import exp
from numpy import sqrt
from numpy import cos
from numpy import e
from numpy import pi


def de(costF, bounds, dim=False, F=0.8, CR=0.8, popSize=False, gens=10):
  if not dim:
    dim = len(bounds)
  if not popSize:
    popSize = 10*dim

  # Population initialization

  #   - array of random numbers in range [0,1]
  pop = np.random.rand(popSize, dim)

  #   - converting bounds into array, T means transposed
  #   - it must be transposed so the boundaries are stored in bmin, bmax
  bmin, bmax = np.asarray(bounds).T

  #   - diff = search range of every parameter (array)
  #   - can't use bmax-bmin, it might result in 0
  diff = np.fabs(bmin - bmax)

  #   - get the population (pop) into boundaries (=ppl)
  #   - (can't do pop*bmax - it wouldn't cover numbers <0)
  ppl = bmin + pop * diff

  # Evaluation of individuals
  costEval = np.asarray([costF(ind) for ind in ppl])

  # Marking the best individual
  bestIndex = np.argmin(costEval)
  bestValue = costEval[bestIndex]
  best = ppl[bestIndex]

  ###
  while gens:
    for i in range(popSize):
      # - choose current individual
      currentIndividual = ppl[i]
      currInd = pop[i]
      # - create a list of indices of other individuals to pick other parents
      indices = [index for index in range(popSize) if index != i]

      # - pick 3 indices from list, don't replace it with anything
      r1, r2, r3 = pop[np.random.choice(indices, 3, replace = False)]

      # Noise vector

      # - this returns parameters ejected from boundaries to the edge...
      # v = np.clip(r1 + F * (r2 - r3), 0, 1)

      v = r1 + F * (r2 - r3)
      # - this returns parameters ejected from boundaries to random position
      # on its side of searched space (>1 right side <0,1>; <1 left side <-1,0>)
        
      v[v>1] = np.random.rand()
      v[v<-1] = -1 + np.random.rand()

      # Crossing
      # - trl = trial vector in interval <0,1>
      trl = np.asarray([v[j] if np.random.rand()<CR
                        else currInd[j] for j in range(dim)])
      
      trial = np.asarray([v[i] if np.random.rand()<CR else ind[i] for i in range(dim)])

      trial = bmin + trl * diff
      
      # Cost evaluation of trial vector
      costTrial = costF(trial)

      #print("Gen"+str(np.abs(10-gens))+":", costTrial, "/", bestValue)
      print("Gen"+str(np.abs(5-gens))+":", trl)
      print("v=",v,"\n"+"currInd=",currInd,"\n")


      # individuals too often in range <0,1>
      # maybe something to do with pop?   !!!!



    #gens -= 1
    gens = False
  ###
"""
  for i in range(gens):
      for j in range(popsize):
          idxs = [idx for idx in range(popsize) if idx != j]
          a, b, c = pop[np.random.choice(idxs, 3, replace = False)]
          mutant = np.clip(a + mut * (b - c), 0, 1)
          cross_points = np.random.rand(dimensions) < crossp
          if not np.any(cross_points):
              cross_points[np.random.randint(0, dimensions)] = True
          trial = np.where(cross_points, mutant, pop[j])
          trial_denorm = min_b + trial * diff
          f = fobj(trial_denorm)
          if f < fitness[j]:
              fitness[j] = f
              pop[j] = trial
              if f < fitness[best_idx]:
                  best_idx = j
                  best = trial_denorm
      yield best, fitness[best_idx]
"""

def costF(v):
	x, y = v
	return -20.0 * exp(-0.2 * sqrt(0.5 * (x**2 + y**2))) - exp(0.5 * (cos(2 * pi * x) + cos(2 * pi * y))) + e + 20


de(costF,[(-5,5)]*2, gens=5)

Gen0: [0.68277766 0.69073323]
v= [0.68277766 0.69073323] 
currInd= [0.67474233 0.6428267 ] 

Gen0: [0.89189722 0.57163422]
v= [0.33919335 0.57163422] 
currInd= [0.89189722 0.68527884] 

Gen0: [0.50464652 0.28608399]
v= [0.50464652 0.28608399] 
currInd= [0.72644406 0.97082907] 

Gen0: [0.22297222 0.68483912]
v= [0.22297222 0.68483912] 
currInd= [0.34518471 0.86813891] 

Gen0: [0.31733992 0.9880377 ]
v= [0.31733992 0.2111429 ] 
currInd= [0.61256052 0.9880377 ] 

Gen0: [0.71705361 0.58126043]
v= [0.71705361 0.58126043] 
currInd= [0.87344614 0.08881212] 

Gen0: [0.59592839 0.91270074]
v= [0.59592839 0.91270074] 
currInd= [0.41527406 0.31660927] 

Gen0: [0.42083853 0.53331197]
v= [0.42083853 0.53331197] 
currInd= [0.00234009 0.98469852] 

Gen0: [0.5085501  0.65846217]
v= [0.20710153 0.65846217] 
currInd= [0.5085501  0.68298456] 

Gen0: [0.88369853 0.83562065]
v= [0.60034017 0.83562065] 
currInd= [0.88369853 0.66504684] 

Gen0: [0.80079039 0.69904574]
v= [0.80079039 0.69904574] 
currInd= [0.